name: Build Test
on:
  pull_request:
    types: [opened, synchronize, reopened]
permissions:
  contents: write
jobs:
  build-test:
    if: ${{ !contains(github.event.pull_request.labels.*.name, 'invalid') }}
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Go 🔧 # Build using latest Go version (stable)
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Node 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 20 # LTS (May 2024 - April 2026)
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Wasm & Web 🔧
        run: |
          cp $(go env GOROOT)/misc/wasm/wasm_exec.js src/assets/wasm/wasm_exec.js

          npm ci
          npm run build-wasm
          npm run build-only
          cp dist/index.html dist/404.html
