name: Build and Deploy
on:
  push:
    branches:
      - master
permissions:
  contents: write
jobs:
  build-and-deploy:
    concurrency: ci-${{ github.ref }} # Recommended if you intend to make multiple deployments in quick succession.
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v4

      - name: Set up Go 🔧 # Build using latest Go version (stable)
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Set up Node 🔧
        uses: actions/setup-node@v4
        with:
          node-version: 20 # LTS (May 2024 - April 2026)
          cache: 'npm'

      - name: Install dependencies
        run: npm install

      - name: Build Wasm & Web 🔧
        run: |
          GOROOT=$(go env GOROOT)
          cp $GOROOT/misc/wasm/wasm_exec.js src/assets/wasm/wasm_exec.js

          npm ci
          npm run build-wasm
          npm run build-only
          cp dist/index.html dist/404.html
          cp LICENSE dist/LICENSE

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist # The folder the action should deploy.
